[package]
name = "lieweb"
version = "0.1.0"
authors = ["zzzdong <kuwater@163.com>"]
edition = "2018"

[dependencies]
bytes = "0.5"
futures = "0.3"
futures-util = "0.3"
http = "0.2"
hyper = "0.13"
lazy_static = "1.4"
log = "0.4"
mime = "0.3"
route-recognizer = "0.1"
serde = "1.0"
serde_json = "1.0"
thiserror = "1.0"
tokio = "0.2"

[dev-dependencies]
env_logger = "0.6"
tokio = { version="0.2", features=["full"] }
serde = { version="1.0", features=["derive"] }
